language: rust
rust:
  - stable
matrix:
  fast_finish: true
cache: cargo
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - liblzo2-dev
      - kcov
  homebrew:
    packages:
      - curl
      - gcc
      - cmake
      - lzo
      - binutils
      - dwarf
      - kcov
    update: true

sudo: required

script:
  - cargo build
  - cargo test --all

after_success:
  - for file in target/debug/borderlands2-*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&  bash <(curl -s https://codecov.io/bash)

