[package]
name = "borderlands2_save_editor"
version = "0.1.0"
authors = ["David Oberacker <david.oberacker@microchip.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
protoc-rust = "2.9.0"

[dependencies]
protobuf = { version = "2.9.0", features = ["with-bytes"] }
minilzo = "0.2.0"
