[package]
name = "borderlands2_save_editor"
version = "0.1.0"
authors = ["David Oberacker <david.oberacker@microchip.com>"]
edition = "2021"

[dependencies]
env_logger = "0.10"
rfd = "0.12.0"
eframe = "0.23.0"

[dependencies.borderlands2]
path = "../borderlands2"





