name: Rust CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt update -y
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - name: Install nightly toolchain
        run: rustup install nightly
      - name: Set default toolchain
        run: rustup default nightly
      - name: Install LLVM Tools
        run: rustup component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
      - name: Install Cargo Nextest
        run: cargo install cargo-nextest
      - name: Install Cargo LLVM-Cov
        run: cargo install cargo-llvm-cov
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo llvm-cov nextest --package borderlands2
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/nextest/default/junit.xml
      - name: Upload Coverage Results
        uses: coverallsapp/github-action@v2
        if: always()
